
services:
    OAS:
        network_mode: host
        volumes:
            - '.:/app/OnmyojiAutoScript:rw'
            - '/etc/localtime:/etc/localtime:ro'
        container_name: 'oas-env'
        image: 'oas-env'
        build:
            context: ./
            dockerfile: deploy/docker/Dockerfile
            # dockerfile: deploy/docker/Dockerfile